"""inital db create

Revision ID: 2849dc717329
Revises: 
Create Date: 2021-02-24 20:19:49.475370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2849dc717329'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bug_tracker_url', sa.String(), nullable=True),
    sa.Column('root_cause', sa.String(), nullable=True),
    sa.Column('who', sa.String(), nullable=True),
    sa.Column('when', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bug_tracker_url')
    )
    op.create_table('root_cause',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('root_cause')
    op.drop_table('bug')
    # ### end Alembic commands ###
